Repository KNU-HAEDAL/2024-Javascript-Algorithm, pull requests merged in 2024-10, with the labels that each got.

#32 Solve: 06 - 실패율
  jijun0129/Algorithm/06.js
  jijun0129/Algorithm/06_book.js
Labels: ✅ Solved

#34 Solve: 06 문제 실패율
  seung365/programmers/06.js
Labels: ✅ Solved

#35 Solve: 문제 6 실패율
  Dobbymin/Algorithm/book/06.js
Labels: ✅ Solved

#37 Solve: 07 - 방문 길이
  jijun0129/Algorithm/07.js
  jijun0129/Algorithm/07_book.js
Labels: ✅ Solved

#39 Solve: 07 방문길이
  seung365/programmers/07.py
Labels: ✅ Solved

#41 Solve: 08 - 괄호 짝 맞추기
  jijun0129/Algorithm/08.in
  jijun0129/Algorithm/08.js
Labels: ✅ Solved

#44 Solve: 09 - 10진수를 2진수로 변환하기
  jijun0129/Algorithm/09.in
  jijun0129/Algorithm/09.js
Labels: ✅ Solved

#43 Solve: 08 문제 괄호 짝 맞추기
  seung365/programmers/08.py
Labels: ✅ Solved

#45 Docs: type - remove 추가
  README.md
Labels: 📖 Docs

#47 Solve: 문제 09 - 10진수를 2진수로 변환하기
  Dobbymin/Algorithm/book/09.js
  Dobbymin/study/join.js
Labels: ✅ Solved

#48 Solve: 09 문제 10진수를 2진수로 변환하기
  seung365/programmers/09.py
Labels: ✅ Solved

#49 Solve: 10 - 괄호 회전하기
  mezzang/book/10.js
Labels: ✅ Solved

#50 Solve: 문제 10 - 괄호 회전하기
  Dobbymin/Algorithm/book/10.js
Labels: ✅ Solved

#51 Solve: 문제 10 괄호 회전하기
  seung365/programmers/10.py
Labels: ✅ Solved

#53 Solve: 문제11 짝지어 제거하기
  seung365/programmers/11.py
Labels: ✅ Solved

#54 Solve: 문제 11 - 짝지어 제거하기
  Dobbymin/Algorithm/book/11.js
Labels: ✅ Solved

#57 Solve: 문제12 주식 가격
  seung365/programmers/12.py
Labels: ✅ Solved

#59 Solve: 문제 12 - 주식 가격
  Dobbymin/Algorithm/book/12.js
Labels: ✅ Solved

#60 Solve: 문제13 크레인 인형 뽑기 게임
  seung365/programmers/13.py
Labels: ✅ Solved

#61 Solve: 13 - 크레인 인형 뽑기 게임
  jijun0129/Algorithm/13.js
  jijun0129/Algorithm/13_book.js
Labels: ✅ Solved

#62 Solve: 문제 13 - 크레인 인형 뽑기 게임
  Dobbymin/Algorithm/book/13.js
Labels: 😢 Fail

#65 Solve: 14 - 표 편집
  jijun0129/Algorithm/14.js
Labels: ✅ Solved

#66 Solve: 문제 15 - 오세푸스 문제
  Dobbymin/Algorithm/book/14.js
Labels: ✅ Solved

#67 Solve : 문제14 표 편집
  seung365/programmers/14.py
Labels: ✅ Solved

#68 Solve: 15 - 요세푸스 문제
  jijun0129/Algorithm/15.js
  jijun0129/Algorithm/15_book.js
Labels: ✅ Solved

#69 Solve: 문제 15 요세푸스 문제
  seung365/programmers/15.py
Labels: ✅ Solved

#70 Solve: 문제 16 - 기능 개발
  Dobbymin/Algorithm/book/16.js
Labels: ✅ Solved

#71 Solve: 문제 15 - 요세푸스 문제
  Dobbymin/Algorithm/book/15.js
Labels: ✅ Solved

#72 Solve: 16 - 기능 개발
  jijun0129/Algorithm/16.js
  jijun0129/Algorithm/16_book.js
Labels: ✅ Solved

#73 Solve: 문제 16 기능 개발
  seung365/programmers/16.py
Labels: ✅ Solved

#74 Solve: 문제 17, 18
  Dobbymin/Algorithm/book/17.js
  Dobbymin/Algorithm/book/18.js
Labels: ✅ Solved

#75 Solve: 18 - 두 개의 수로 특정 값 만들기
  jijun0129/Algorithm/17.js
  jijun0129/Algorithm/18.js
Labels: ✅ Solved

#76 Solve: 문제 17, 18
  seung365/programmers/17.py
  seung365/programmers/18.py
Labels: ✅ Solved
